### ISSUE TITLE
markers blinking

### ISSUE THREAD

**Issue by ochanje210** [sv-bootcamp/goober-mobile#34]
https://github.com/airbnb/react-native-maps/issues/683
the above may help

**Comment by slimmii** [comment]
I'm experiencing the same issue with 0.11.x on iOS. 0.8.x doesn't have the problem.

**Comment by ochanje210** [comment]
@slimmii u can check this! : https://github.com/airbnb/react-native-maps/commit/27f9c30474f20c6911e9d6eade52fc5f11e4aa3a
